/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package newpackage;

import java.util.ArrayList;

/**
 *
 * @author RUKIYE
 */

//I created all this jframe by myself.(There is no guide video.)

//NAME-SURNAME: RUKİYE SUEDA AKKUŞ
//NUMBER: 20212022041
//DEPARTMENT: SOFTWARE ENGINEERING

public class Admin extends javax.swing.JFrame {

    /**
     * Creates new form Admin
     */
    static ArrayList<String> priceList=new ArrayList<>();//An arraylist to help defining price of foods
    public Admin() {
        initComponents();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        priceofRAGU = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        priceofARABIATA = new javax.swing.JTextField();
        priceofALFREDO = new javax.swing.JTextField();
        priceofFETTUCCINE = new javax.swing.JTextField();
        priceofSPAGHETTIBOLOGNESE = new javax.swing.JTextField();
        priceofCAPTAINSSALAD = new javax.swing.JTextField();
        priceofCREAMYSTEAK = new javax.swing.JTextField();
        priceofFOURCHEESESALAD = new javax.swing.JTextField();
        priceofCANNOLI = new javax.swing.JTextField();
        priceofSANSEBASTIAN = new javax.swing.JTextField();
        priceofMARCHESI = new javax.swing.JTextField();
        priceofPANNACOTTA = new javax.swing.JTextField();
        priceofTORTACAPRESE = new javax.swing.JTextField();
        priceofBROWNI = new javax.swing.JTextField();
        priceofBEEFPIZZA = new javax.swing.JTextField();
        priceofCARPACCIOPIZZA = new javax.swing.JTextField();
        priceofBOLOGNESEPIZZA = new javax.swing.JTextField();
        priceofMARGHERITA = new javax.swing.JTextField();
        priceofCHICKENPIZZA = new javax.swing.JTextField();
        priceofMILKSHAKE = new javax.swing.JTextField();
        priceofCOCKTAILS = new javax.swing.JTextField();
        priceofCOFFEE = new javax.swing.JTextField();
        priceofSOFTDRINKS = new javax.swing.JTextField();
        saveTORTACAPRESE = new javax.swing.JButton();
        saveSOFTDRINKS = new javax.swing.JButton();
        saveCARPACCIOPIZZA = new javax.swing.JButton();
        saveBOLOGNESEPIZZA = new javax.swing.JButton();
        saveMARGHERITA = new javax.swing.JButton();
        saveCHICKENPIZZA = new javax.swing.JButton();
        saveMILKSHAKES = new javax.swing.JButton();
        saveCOCKTAILS = new javax.swing.JButton();
        saveCOFFEE = new javax.swing.JButton();
        saveBROWNI = new javax.swing.JButton();
        saveBEEFPIZZA = new javax.swing.JButton();
        saveRAGU = new javax.swing.JButton();
        saveARABIATA = new javax.swing.JButton();
        saveBOLOGNESE = new javax.swing.JButton();
        saveFETTUCCINE = new javax.swing.JButton();
        saveALFREDO = new javax.swing.JButton();
        saveCREAMYSALAD = new javax.swing.JButton();
        saveCAPTAINSSALAD = new javax.swing.JButton();
        saveFOURCHEESESALAD = new javax.swing.JButton();
        saveMARCHESI = new javax.swing.JButton();
        saveCANNOLI = new javax.swing.JButton();
        saveSANSEBASTIAN = new javax.swing.JButton();
        savePANNACOTTA = new javax.swing.JButton();
        jLabel32 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CannolıRestaurantAdminPage");

        jPanel1.setBackground(new java.awt.Color(245, 240, 240));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setForeground(new java.awt.Color(0, 153, 153));
        jPanel1.setToolTipText("");

        jLabel1.setFont(new java.awt.Font("STLiti", 3, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText(" CANNOLI RESTAURANT");

        jLabel2.setFont(new java.awt.Font("STLiti", 3, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("              pricing page for managers");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        jLabel3.setText("MARCHESI");
        jLabel3.setToolTipText("");

        priceofRAGU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                priceofRAGUActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        jLabel10.setText("BEEF FETTUCCINE ALFREDO");
        jLabel10.setToolTipText("");

        jLabel12.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        jLabel12.setText("FETTUCCINE DI PARMA");
        jLabel12.setToolTipText("");

        jLabel13.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        jLabel13.setText("BEEF PENNE ARABIATA");
        jLabel13.setToolTipText("");

        jLabel14.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        jLabel14.setText("CREAMY STEAK SALAD");
        jLabel14.setToolTipText("");

        jLabel15.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        jLabel15.setText("CAPTAIN'S SALAD");
        jLabel15.setToolTipText("");

        jLabel16.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        jLabel16.setText("CANNOLI");
        jLabel16.setToolTipText("");

        jLabel17.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        jLabel17.setText("FOUR CHEESE SALAD");
        jLabel17.setToolTipText("");

        jLabel18.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        jLabel18.setText("RAGÙ");
        jLabel18.setToolTipText("");

        jLabel19.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        jLabel19.setText("SAN SEBASTIAN");
        jLabel19.setToolTipText("");

        jLabel20.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        jLabel20.setText("SOFT DRINKS");
        jLabel20.setToolTipText("");

        jLabel21.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        jLabel21.setText("PANNA COTTA");
        jLabel21.setToolTipText("");

        jLabel22.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        jLabel22.setText("COCKTAILS");
        jLabel22.setToolTipText("");

        jLabel23.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        jLabel23.setText("COFFEE");
        jLabel23.setToolTipText("");

        jLabel24.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        jLabel24.setText("CHICKEN PIZZA WITH PESTO");
        jLabel24.setToolTipText("");

        jLabel25.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        jLabel25.setText("MILKSHAKE'S / FROZEN");
        jLabel25.setToolTipText("");

        jLabel26.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        jLabel26.setText("BOLOGNESE PIZZA");
        jLabel26.setToolTipText("");

        jLabel27.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        jLabel27.setText("MARGHERITA");
        jLabel27.setToolTipText("");

        jLabel28.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        jLabel28.setText("BEEF PIZZA");
        jLabel28.setToolTipText("");

        jLabel29.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        jLabel29.setText("CARPACCIO PIZZA");
        jLabel29.setToolTipText("");

        jLabel30.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        jLabel30.setText("TORTA CAPRESE");
        jLabel30.setToolTipText("");

        jLabel31.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        jLabel31.setText("BROWNI");
        jLabel31.setToolTipText("");

        priceofARABIATA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                priceofARABIATAActionPerformed(evt);
            }
        });

        priceofALFREDO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                priceofALFREDOActionPerformed(evt);
            }
        });

        priceofFETTUCCINE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                priceofFETTUCCINEActionPerformed(evt);
            }
        });

        priceofSPAGHETTIBOLOGNESE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                priceofSPAGHETTIBOLOGNESEActionPerformed(evt);
            }
        });

        priceofCAPTAINSSALAD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                priceofCAPTAINSSALADActionPerformed(evt);
            }
        });

        priceofCREAMYSTEAK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                priceofCREAMYSTEAKActionPerformed(evt);
            }
        });

        priceofFOURCHEESESALAD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                priceofFOURCHEESESALADActionPerformed(evt);
            }
        });

        priceofCANNOLI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                priceofCANNOLIActionPerformed(evt);
            }
        });

        priceofSANSEBASTIAN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                priceofSANSEBASTIANActionPerformed(evt);
            }
        });

        priceofMARCHESI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                priceofMARCHESIActionPerformed(evt);
            }
        });

        priceofPANNACOTTA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                priceofPANNACOTTAActionPerformed(evt);
            }
        });

        priceofTORTACAPRESE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                priceofTORTACAPRESEActionPerformed(evt);
            }
        });

        priceofBROWNI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                priceofBROWNIActionPerformed(evt);
            }
        });

        priceofBEEFPIZZA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                priceofBEEFPIZZAActionPerformed(evt);
            }
        });

        priceofCARPACCIOPIZZA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                priceofCARPACCIOPIZZAActionPerformed(evt);
            }
        });

        priceofBOLOGNESEPIZZA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                priceofBOLOGNESEPIZZAActionPerformed(evt);
            }
        });

        priceofMARGHERITA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                priceofMARGHERITAActionPerformed(evt);
            }
        });

        priceofCHICKENPIZZA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                priceofCHICKENPIZZAActionPerformed(evt);
            }
        });

        priceofMILKSHAKE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                priceofMILKSHAKEActionPerformed(evt);
            }
        });

        priceofCOCKTAILS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                priceofCOCKTAILSActionPerformed(evt);
            }
        });

        priceofCOFFEE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                priceofCOFFEEActionPerformed(evt);
            }
        });

        priceofSOFTDRINKS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                priceofSOFTDRINKSActionPerformed(evt);
            }
        });

        saveTORTACAPRESE.setBackground(new java.awt.Color(255, 255, 255));
        saveTORTACAPRESE.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        saveTORTACAPRESE.setForeground(new java.awt.Color(204, 153, 51));
        saveTORTACAPRESE.setText("save");
        saveTORTACAPRESE.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        saveTORTACAPRESE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveTORTACAPRESEActionPerformed(evt);
            }
        });

        saveSOFTDRINKS.setBackground(new java.awt.Color(255, 255, 255));
        saveSOFTDRINKS.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        saveSOFTDRINKS.setForeground(new java.awt.Color(204, 153, 51));
        saveSOFTDRINKS.setText("save");
        saveSOFTDRINKS.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        saveSOFTDRINKS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveSOFTDRINKSActionPerformed(evt);
            }
        });

        saveCARPACCIOPIZZA.setBackground(new java.awt.Color(255, 255, 255));
        saveCARPACCIOPIZZA.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        saveCARPACCIOPIZZA.setForeground(new java.awt.Color(204, 153, 51));
        saveCARPACCIOPIZZA.setText("save");
        saveCARPACCIOPIZZA.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        saveCARPACCIOPIZZA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveCARPACCIOPIZZAActionPerformed(evt);
            }
        });

        saveBOLOGNESEPIZZA.setBackground(new java.awt.Color(255, 255, 255));
        saveBOLOGNESEPIZZA.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        saveBOLOGNESEPIZZA.setForeground(new java.awt.Color(204, 153, 51));
        saveBOLOGNESEPIZZA.setText("save");
        saveBOLOGNESEPIZZA.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        saveBOLOGNESEPIZZA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBOLOGNESEPIZZAActionPerformed(evt);
            }
        });

        saveMARGHERITA.setBackground(new java.awt.Color(255, 255, 255));
        saveMARGHERITA.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        saveMARGHERITA.setForeground(new java.awt.Color(204, 153, 51));
        saveMARGHERITA.setText("save");
        saveMARGHERITA.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        saveMARGHERITA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveMARGHERITAActionPerformed(evt);
            }
        });

        saveCHICKENPIZZA.setBackground(new java.awt.Color(255, 255, 255));
        saveCHICKENPIZZA.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        saveCHICKENPIZZA.setForeground(new java.awt.Color(204, 153, 51));
        saveCHICKENPIZZA.setText("save");
        saveCHICKENPIZZA.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        saveCHICKENPIZZA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveCHICKENPIZZAActionPerformed(evt);
            }
        });

        saveMILKSHAKES.setBackground(new java.awt.Color(255, 255, 255));
        saveMILKSHAKES.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        saveMILKSHAKES.setForeground(new java.awt.Color(204, 153, 51));
        saveMILKSHAKES.setText("save");
        saveMILKSHAKES.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        saveMILKSHAKES.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveMILKSHAKESActionPerformed(evt);
            }
        });

        saveCOCKTAILS.setBackground(new java.awt.Color(255, 255, 255));
        saveCOCKTAILS.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        saveCOCKTAILS.setForeground(new java.awt.Color(204, 153, 51));
        saveCOCKTAILS.setText("save");
        saveCOCKTAILS.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        saveCOCKTAILS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveCOCKTAILSActionPerformed(evt);
            }
        });

        saveCOFFEE.setBackground(new java.awt.Color(255, 255, 255));
        saveCOFFEE.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        saveCOFFEE.setForeground(new java.awt.Color(204, 153, 51));
        saveCOFFEE.setText("save");
        saveCOFFEE.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        saveCOFFEE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveCOFFEEActionPerformed(evt);
            }
        });

        saveBROWNI.setBackground(new java.awt.Color(255, 255, 255));
        saveBROWNI.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        saveBROWNI.setForeground(new java.awt.Color(204, 153, 51));
        saveBROWNI.setText("save");
        saveBROWNI.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        saveBROWNI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBROWNIActionPerformed(evt);
            }
        });

        saveBEEFPIZZA.setBackground(new java.awt.Color(255, 255, 255));
        saveBEEFPIZZA.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        saveBEEFPIZZA.setForeground(new java.awt.Color(204, 153, 51));
        saveBEEFPIZZA.setText("save");
        saveBEEFPIZZA.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        saveBEEFPIZZA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBEEFPIZZAActionPerformed(evt);
            }
        });

        saveRAGU.setBackground(new java.awt.Color(255, 255, 255));
        saveRAGU.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        saveRAGU.setForeground(new java.awt.Color(204, 153, 51));
        saveRAGU.setText("save");
        saveRAGU.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        saveRAGU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveRAGUActionPerformed(evt);
            }
        });

        saveARABIATA.setBackground(new java.awt.Color(255, 255, 255));
        saveARABIATA.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        saveARABIATA.setForeground(new java.awt.Color(204, 153, 51));
        saveARABIATA.setText("save");
        saveARABIATA.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        saveARABIATA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveARABIATAActionPerformed(evt);
            }
        });

        saveBOLOGNESE.setBackground(new java.awt.Color(255, 255, 255));
        saveBOLOGNESE.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        saveBOLOGNESE.setForeground(new java.awt.Color(204, 153, 51));
        saveBOLOGNESE.setText("save");
        saveBOLOGNESE.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        saveBOLOGNESE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBOLOGNESEActionPerformed(evt);
            }
        });

        saveFETTUCCINE.setBackground(new java.awt.Color(255, 255, 255));
        saveFETTUCCINE.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        saveFETTUCCINE.setForeground(new java.awt.Color(204, 153, 51));
        saveFETTUCCINE.setText("save");
        saveFETTUCCINE.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        saveFETTUCCINE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveFETTUCCINEActionPerformed(evt);
            }
        });

        saveALFREDO.setBackground(new java.awt.Color(255, 255, 255));
        saveALFREDO.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        saveALFREDO.setForeground(new java.awt.Color(204, 153, 51));
        saveALFREDO.setText("save");
        saveALFREDO.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        saveALFREDO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveALFREDOActionPerformed(evt);
            }
        });

        saveCREAMYSALAD.setBackground(new java.awt.Color(255, 255, 255));
        saveCREAMYSALAD.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        saveCREAMYSALAD.setForeground(new java.awt.Color(204, 153, 51));
        saveCREAMYSALAD.setText("save");
        saveCREAMYSALAD.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        saveCREAMYSALAD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveCREAMYSALADActionPerformed(evt);
            }
        });

        saveCAPTAINSSALAD.setBackground(new java.awt.Color(255, 255, 255));
        saveCAPTAINSSALAD.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        saveCAPTAINSSALAD.setForeground(new java.awt.Color(204, 153, 51));
        saveCAPTAINSSALAD.setText("save");
        saveCAPTAINSSALAD.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        saveCAPTAINSSALAD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveCAPTAINSSALADActionPerformed(evt);
            }
        });

        saveFOURCHEESESALAD.setBackground(new java.awt.Color(255, 255, 255));
        saveFOURCHEESESALAD.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        saveFOURCHEESESALAD.setForeground(new java.awt.Color(204, 153, 51));
        saveFOURCHEESESALAD.setText("save");
        saveFOURCHEESESALAD.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        saveFOURCHEESESALAD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveFOURCHEESESALADActionPerformed(evt);
            }
        });

        saveMARCHESI.setBackground(new java.awt.Color(255, 255, 255));
        saveMARCHESI.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        saveMARCHESI.setForeground(new java.awt.Color(204, 153, 51));
        saveMARCHESI.setText("save");
        saveMARCHESI.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        saveMARCHESI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveMARCHESIActionPerformed(evt);
            }
        });

        saveCANNOLI.setBackground(new java.awt.Color(255, 255, 255));
        saveCANNOLI.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        saveCANNOLI.setForeground(new java.awt.Color(204, 153, 51));
        saveCANNOLI.setText("save");
        saveCANNOLI.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        saveCANNOLI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveCANNOLIActionPerformed(evt);
            }
        });

        saveSANSEBASTIAN.setBackground(new java.awt.Color(255, 255, 255));
        saveSANSEBASTIAN.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        saveSANSEBASTIAN.setForeground(new java.awt.Color(204, 153, 51));
        saveSANSEBASTIAN.setText("save");
        saveSANSEBASTIAN.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        saveSANSEBASTIAN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveSANSEBASTIANActionPerformed(evt);
            }
        });

        savePANNACOTTA.setBackground(new java.awt.Color(255, 255, 255));
        savePANNACOTTA.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        savePANNACOTTA.setForeground(new java.awt.Color(204, 153, 51));
        savePANNACOTTA.setText("save");
        savePANNACOTTA.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        savePANNACOTTA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savePANNACOTTAActionPerformed(evt);
            }
        });

        jLabel32.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        jLabel32.setText("SPAGHETTI BOLOGNESE");
        jLabel32.setToolTipText("");

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jButton1.setText("log out");
        jButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 431, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(priceofPANNACOTTA, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(savePANNACOTTA, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(priceofSANSEBASTIAN, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(saveSANSEBASTIAN, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(priceofCANNOLI, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(saveCANNOLI, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(priceofMARCHESI, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(saveMARCHESI, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(379, 379, 379)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE)
                                                            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                            .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addGap(12, 12, 12)))
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                        .addComponent(priceofRAGU, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(18, 18, 18)
                                                        .addComponent(saveRAGU, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                        .addComponent(priceofARABIATA, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(18, 18, 18)
                                                        .addComponent(saveARABIATA, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                        .addComponent(priceofALFREDO, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(18, 18, 18)
                                                        .addComponent(saveALFREDO, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                        .addComponent(priceofFETTUCCINE, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(18, 18, 18)
                                                        .addComponent(saveFETTUCCINE, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(jLabel32, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                .addGap(12, 12, 12)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                        .addComponent(priceofFOURCHEESESALAD, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(18, 18, 18)
                                                        .addComponent(saveFOURCHEESESALAD, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                        .addComponent(priceofCREAMYSTEAK, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(18, 18, 18)
                                                        .addComponent(saveCREAMYSALAD, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                        .addComponent(priceofCAPTAINSSALAD, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(18, 18, 18)
                                                        .addComponent(saveCAPTAINSSALAD, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                        .addComponent(priceofSPAGHETTIBOLOGNESE, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(18, 18, 18)
                                                        .addComponent(saveBOLOGNESE, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                        .addGap(47, 47, 47))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(303, 303, 303)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(priceofTORTACAPRESE, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(saveTORTACAPRESE, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(jLabel24, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE)
                                                .addComponent(jLabel27, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jLabel26, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jLabel29, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jLabel28, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jLabel31, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                    .addComponent(priceofBROWNI, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(18, 18, 18)
                                                    .addComponent(saveBROWNI, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                    .addComponent(priceofBEEFPIZZA, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(18, 18, 18)
                                                    .addComponent(saveBEEFPIZZA, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                    .addComponent(priceofCARPACCIOPIZZA, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(18, 18, 18)
                                                    .addComponent(saveCARPACCIOPIZZA, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                    .addComponent(priceofBOLOGNESEPIZZA, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(18, 18, 18)
                                                    .addComponent(saveBOLOGNESEPIZZA, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                    .addComponent(priceofMARGHERITA, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(18, 18, 18)
                                                    .addComponent(saveMARGHERITA, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                    .addComponent(priceofCHICKENPIZZA, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(18, 18, 18)
                                                    .addComponent(saveCHICKENPIZZA, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel25, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                .addComponent(priceofMILKSHAKE, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(saveMILKSHAKES, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                .addComponent(priceofCOCKTAILS, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(saveCOCKTAILS, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                .addComponent(priceofCOFFEE, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(saveCOFFEE, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                .addComponent(priceofSOFTDRINKS, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(saveSOFTDRINKS, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(priceofRAGU, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(priceofTORTACAPRESE, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(saveTORTACAPRESE, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                        .addComponent(saveRAGU, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(priceofBROWNI, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(priceofARABIATA, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(saveBROWNI, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                    .addComponent(saveARABIATA, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE))
                .addGap(5, 5, 5)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(priceofBEEFPIZZA, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(priceofALFREDO, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(saveBEEFPIZZA, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                    .addComponent(saveALFREDO, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(priceofCARPACCIOPIZZA, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(priceofFETTUCCINE, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(saveCARPACCIOPIZZA, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                    .addComponent(saveFETTUCCINE, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(priceofBOLOGNESEPIZZA, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(priceofSPAGHETTIBOLOGNESE, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(saveBOLOGNESEPIZZA, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                    .addComponent(saveBOLOGNESE, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                    .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(priceofMARGHERITA, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(priceofCAPTAINSSALAD, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(saveMARGHERITA, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                    .addComponent(saveCAPTAINSSALAD, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(priceofCHICKENPIZZA, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(priceofCREAMYSTEAK, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(saveCHICKENPIZZA, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                    .addComponent(saveCREAMYSALAD, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel25, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(saveFOURCHEESESALAD, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(priceofMILKSHAKE, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(saveMILKSHAKES, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                        .addComponent(priceofFOURCHEESESALAD, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel22, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(priceofCOCKTAILS, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(saveCOCKTAILS, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                        .addComponent(saveCANNOLI, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                        .addComponent(priceofCANNOLI, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(priceofCOFFEE, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(priceofSANSEBASTIAN, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(saveCOFFEE, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                    .addComponent(saveSANSEBASTIAN, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(priceofSOFTDRINKS, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(priceofMARCHESI, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(saveSOFTDRINKS, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                    .addComponent(saveMARCHESI, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(priceofPANNACOTTA, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(savePANNACOTTA, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void priceofRAGUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_priceofRAGUActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_priceofRAGUActionPerformed

    private void priceofARABIATAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_priceofARABIATAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_priceofARABIATAActionPerformed

    private void priceofALFREDOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_priceofALFREDOActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_priceofALFREDOActionPerformed

    private void priceofFETTUCCINEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_priceofFETTUCCINEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_priceofFETTUCCINEActionPerformed

    private void priceofSPAGHETTIBOLOGNESEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_priceofSPAGHETTIBOLOGNESEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_priceofSPAGHETTIBOLOGNESEActionPerformed

    private void priceofCAPTAINSSALADActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_priceofCAPTAINSSALADActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_priceofCAPTAINSSALADActionPerformed

    private void priceofCREAMYSTEAKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_priceofCREAMYSTEAKActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_priceofCREAMYSTEAKActionPerformed

    private void priceofFOURCHEESESALADActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_priceofFOURCHEESESALADActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_priceofFOURCHEESESALADActionPerformed

    private void priceofCANNOLIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_priceofCANNOLIActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_priceofCANNOLIActionPerformed

    private void priceofSANSEBASTIANActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_priceofSANSEBASTIANActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_priceofSANSEBASTIANActionPerformed

    private void priceofMARCHESIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_priceofMARCHESIActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_priceofMARCHESIActionPerformed

    private void priceofPANNACOTTAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_priceofPANNACOTTAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_priceofPANNACOTTAActionPerformed

    private void priceofTORTACAPRESEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_priceofTORTACAPRESEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_priceofTORTACAPRESEActionPerformed

    private void priceofBROWNIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_priceofBROWNIActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_priceofBROWNIActionPerformed

    private void priceofBEEFPIZZAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_priceofBEEFPIZZAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_priceofBEEFPIZZAActionPerformed

    private void priceofCARPACCIOPIZZAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_priceofCARPACCIOPIZZAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_priceofCARPACCIOPIZZAActionPerformed

    private void priceofBOLOGNESEPIZZAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_priceofBOLOGNESEPIZZAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_priceofBOLOGNESEPIZZAActionPerformed

    private void priceofMARGHERITAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_priceofMARGHERITAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_priceofMARGHERITAActionPerformed

    private void priceofCHICKENPIZZAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_priceofCHICKENPIZZAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_priceofCHICKENPIZZAActionPerformed

    private void priceofMILKSHAKEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_priceofMILKSHAKEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_priceofMILKSHAKEActionPerformed

    private void priceofCOCKTAILSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_priceofCOCKTAILSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_priceofCOCKTAILSActionPerformed

    private void priceofCOFFEEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_priceofCOFFEEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_priceofCOFFEEActionPerformed

    private void priceofSOFTDRINKSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_priceofSOFTDRINKSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_priceofSOFTDRINKSActionPerformed

    private void saveRAGUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveRAGUActionPerformed
       priceList.add("RAGU,"+priceofRAGU.getText());//Adding material to arraylist
    }//GEN-LAST:event_saveRAGUActionPerformed

    private void saveARABIATAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveARABIATAActionPerformed
      priceList.add("ARABIATA,"+priceofARABIATA.getText());//Adding material to arraylist          
    }//GEN-LAST:event_saveARABIATAActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Login lgn= new Login();//?
        lgn.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void saveALFREDOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveALFREDOActionPerformed
     priceList.add("ALFREDO,"+priceofALFREDO.getText());//Adding material to arraylist
    }//GEN-LAST:event_saveALFREDOActionPerformed

    private void saveFETTUCCINEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveFETTUCCINEActionPerformed
      priceList.add("FETTUCCINE,"+priceofFETTUCCINE.getText());//Adding material to arraylist
    }//GEN-LAST:event_saveFETTUCCINEActionPerformed

    private void saveBOLOGNESEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBOLOGNESEActionPerformed
        priceList.add("SPAGHETTIBOLOGNESE,"+priceofSPAGHETTIBOLOGNESE.getText());//Adding material to arraylist
    }//GEN-LAST:event_saveBOLOGNESEActionPerformed

    private void saveCAPTAINSSALADActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveCAPTAINSSALADActionPerformed
        priceList.add("CAPTAINSSALAD,"+priceofCAPTAINSSALAD.getText());//Adding material to arraylist
    }//GEN-LAST:event_saveCAPTAINSSALADActionPerformed

    private void saveCREAMYSALADActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveCREAMYSALADActionPerformed
        priceList.add("CREAMYSALAD,"+priceofCREAMYSTEAK.getText());//Adding material to arraylist
    }//GEN-LAST:event_saveCREAMYSALADActionPerformed

    private void saveFOURCHEESESALADActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveFOURCHEESESALADActionPerformed
        priceList.add("FOURCHEESESALAD,"+priceofFOURCHEESESALAD.getText());//Adding material to arraylist
    }//GEN-LAST:event_saveFOURCHEESESALADActionPerformed

    private void saveCANNOLIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveCANNOLIActionPerformed
        priceList.add("CANNOLI,"+priceofCANNOLI.getText());//Adding material to arraylist...
    }//GEN-LAST:event_saveCANNOLIActionPerformed

    private void saveSANSEBASTIANActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveSANSEBASTIANActionPerformed
        priceList.add("SANSEBASTIAN,"+priceofSANSEBASTIAN.getText());
    }//GEN-LAST:event_saveSANSEBASTIANActionPerformed

    private void saveMARCHESIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveMARCHESIActionPerformed
        priceList.add("MARCHESI,"+priceofMARCHESI.getText());
    }//GEN-LAST:event_saveMARCHESIActionPerformed

    private void savePANNACOTTAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savePANNACOTTAActionPerformed
        priceList.add("PANNACOTTA,"+priceofPANNACOTTA.getText());
    }//GEN-LAST:event_savePANNACOTTAActionPerformed

    private void saveTORTACAPRESEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveTORTACAPRESEActionPerformed
        priceList.add("TORTACAPRESE,"+priceofTORTACAPRESE.getText());
    }//GEN-LAST:event_saveTORTACAPRESEActionPerformed

    private void saveBROWNIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBROWNIActionPerformed
        priceList.add("BROWNI,"+priceofBROWNI.getText());
    }//GEN-LAST:event_saveBROWNIActionPerformed

    private void saveBEEFPIZZAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBEEFPIZZAActionPerformed
        priceList.add("BEEFPIZZA,"+priceofBEEFPIZZA.getText());
    }//GEN-LAST:event_saveBEEFPIZZAActionPerformed

    private void saveCARPACCIOPIZZAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveCARPACCIOPIZZAActionPerformed
        priceList.add("CARPACCIOPIZZA,"+priceofCARPACCIOPIZZA.getText());
    }//GEN-LAST:event_saveCARPACCIOPIZZAActionPerformed

    private void saveBOLOGNESEPIZZAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBOLOGNESEPIZZAActionPerformed
        priceList.add("BOLOGNESEPIZZA,"+priceofBOLOGNESEPIZZA.getText());
    }//GEN-LAST:event_saveBOLOGNESEPIZZAActionPerformed

    private void saveMARGHERITAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveMARGHERITAActionPerformed
        priceList.add("MARGHERITA,"+priceofMARGHERITA.getText());
    }//GEN-LAST:event_saveMARGHERITAActionPerformed

    private void saveCHICKENPIZZAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveCHICKENPIZZAActionPerformed
        priceList.add("CHICKENPIZZA,"+priceofCHICKENPIZZA.getText());
    }//GEN-LAST:event_saveCHICKENPIZZAActionPerformed

    private void saveMILKSHAKESActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveMILKSHAKESActionPerformed
        priceList.add("MILKSHAKES,"+priceofMILKSHAKE.getText());
    }//GEN-LAST:event_saveMILKSHAKESActionPerformed

    private void saveCOCKTAILSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveCOCKTAILSActionPerformed
        priceList.add("COCKTAILS,"+priceofCOCKTAILS.getText());
    }//GEN-LAST:event_saveCOCKTAILSActionPerformed

    private void saveCOFFEEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveCOFFEEActionPerformed
        priceList.add("COFFEE,"+priceofCOFFEE.getText());
    }//GEN-LAST:event_saveCOFFEEActionPerformed

    private void saveSOFTDRINKSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveSOFTDRINKSActionPerformed
        priceList.add("SOFTDRINKS,"+priceofSOFTDRINKS.getText());
    }//GEN-LAST:event_saveSOFTDRINKSActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admin().setVisible(true);//?
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField priceofALFREDO;
    private javax.swing.JTextField priceofARABIATA;
    private javax.swing.JTextField priceofBEEFPIZZA;
    private javax.swing.JTextField priceofBOLOGNESEPIZZA;
    private javax.swing.JTextField priceofBROWNI;
    private javax.swing.JTextField priceofCANNOLI;
    private javax.swing.JTextField priceofCAPTAINSSALAD;
    private javax.swing.JTextField priceofCARPACCIOPIZZA;
    private javax.swing.JTextField priceofCHICKENPIZZA;
    private javax.swing.JTextField priceofCOCKTAILS;
    private javax.swing.JTextField priceofCOFFEE;
    private javax.swing.JTextField priceofCREAMYSTEAK;
    private javax.swing.JTextField priceofFETTUCCINE;
    private javax.swing.JTextField priceofFOURCHEESESALAD;
    private javax.swing.JTextField priceofMARCHESI;
    private javax.swing.JTextField priceofMARGHERITA;
    private javax.swing.JTextField priceofMILKSHAKE;
    private javax.swing.JTextField priceofPANNACOTTA;
    private javax.swing.JTextField priceofRAGU;
    private javax.swing.JTextField priceofSANSEBASTIAN;
    private javax.swing.JTextField priceofSOFTDRINKS;
    private javax.swing.JTextField priceofSPAGHETTIBOLOGNESE;
    private javax.swing.JTextField priceofTORTACAPRESE;
    private javax.swing.JButton saveALFREDO;
    private javax.swing.JButton saveARABIATA;
    private javax.swing.JButton saveBEEFPIZZA;
    private javax.swing.JButton saveBOLOGNESE;
    private javax.swing.JButton saveBOLOGNESEPIZZA;
    private javax.swing.JButton saveBROWNI;
    private javax.swing.JButton saveCANNOLI;
    private javax.swing.JButton saveCAPTAINSSALAD;
    private javax.swing.JButton saveCARPACCIOPIZZA;
    private javax.swing.JButton saveCHICKENPIZZA;
    private javax.swing.JButton saveCOCKTAILS;
    private javax.swing.JButton saveCOFFEE;
    private javax.swing.JButton saveCREAMYSALAD;
    private javax.swing.JButton saveFETTUCCINE;
    private javax.swing.JButton saveFOURCHEESESALAD;
    private javax.swing.JButton saveMARCHESI;
    private javax.swing.JButton saveMARGHERITA;
    private javax.swing.JButton saveMILKSHAKES;
    private javax.swing.JButton savePANNACOTTA;
    private javax.swing.JButton saveRAGU;
    private javax.swing.JButton saveSANSEBASTIAN;
    private javax.swing.JButton saveSOFTDRINKS;
    private javax.swing.JButton saveTORTACAPRESE;
    // End of variables declaration//GEN-END:variables
}
